[package]
name = "lodeframe"
description = "A minimal, lightweight Minecraft: Java Edition server library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
lodeframe-text.workspace = true
lodeframe-protocol.workspace = true
lodeframe-macros.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "time", "rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
trybuild.workspace = true
