// SPDX-License-Identifier: Apache-2.0 OR MIT
//! Turns the data generator's reports into Rust source. Pure: no I/O, so it is testable.

use std::{
    collections::{BTreeMap, HashMap},
    fmt::Write,
};

use serde_json::Value;

use crate::Result;

const HEADER: &str = "// SPDX-License-Identifier: Apache-2.0 OR MIT\n\
                      // @generated by `cargo xtask datagen`. Do not edit.\n\
                      #![allow(missing_docs)]\n\n";

/// Everything the generator reads.
pub struct Input {
    pub name: String,
    pub protocol_version: i64,
    pub world_version: i64,
    pub blocks: Value,
    pub packets: Value,
    pub registries: Value,
    /// `(registry id, sorted entry names)` for the data-driven registries the client syncs.
    pub datapack_registries: Vec<(String, Vec<String>)>,
    /// Raw tag files: registry name (`block`, `worldgen/biome`) -> tag name -> `values`.
    pub tags: BTreeMap<String, BTreeMap<String, Vec<String>>>,
}

/// `(file name, source)` for every generated file.
pub fn generate(input: &Input) -> Result<Vec<(&'static str, String)>> {
    Ok(vec![
        ("version.rs", version(input)),
        ("packet_ids.rs", packet_ids(&input.packets)?),
        ("blocks.rs", blocks(&input.blocks, &input.registries)?),
        ("entity_types.rs", entity_types(&input.registries)?),
        (
            "datapack_registries.rs",
            datapack_registries(&input.datapack_registries)?,
        ),
        ("tags.rs", tags(input)?),
    ])
}

fn version(i: &Input) -> String {
    format!(
        "{HEADER}/// The Minecraft version this crate speaks.\n\
         pub const VERSION_NAME: &str = {:?};\n\
         /// Its protocol version number.\n\
         pub const PROTOCOL_VERSION: i32 = {};\n\
         /// Its world (chunk format) version number.\n\
         pub const WORLD_VERSION: i32 = {};\n",
        i.name, i.protocol_version, i.world_version
    )
}

/// `minecraft:oak_stairs` -> `OAK_STAIRS`.
fn const_name(name: &str) -> Result<String> {
    let local = name.split_once(':').map_or(name, |(_, l)| l);
    let up: String = local
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    if up.is_empty() || up.starts_with(|c: char| c.is_ascii_digit()) {
        return Err(format!("{name} cannot be a constant name").into());
    }
    Ok(up)
}

/// `(name, protocol_id)` of a packet or registry entry list, ordered by id.
fn entries_by_id(v: &Value, what: &str) -> Result<Vec<(String, u32)>> {
    let map = v
        .as_object()
        .ok_or_else(|| format!("{what}: expected an object"))?;
    let mut out = Vec::with_capacity(map.len());
    for (name, e) in map {
        let id = e["protocol_id"]
            .as_u64()
            .and_then(|id| u32::try_from(id).ok())
            .ok_or_else(|| format!("{what}: {name} has no protocol_id"))?;
        out.push((name.clone(), id));
    }
    out.sort_by_key(|(_, id)| *id);
    Ok(out)
}

/// Names of a registry ordered by protocol id, which must be 0..N with no gaps.
fn registry_names(registries: &Value, key: &str) -> Result<Vec<String>> {
    let entries = entries_by_id(&registries[key]["entries"], key)?;
    for (i, (name, id)) in entries.iter().enumerate() {
        if *id as usize != i {
            return Err(format!(
                "{key}: protocol ids are not dense (at {name}: {id}, expected {i})"
            )
            .into());
        }
    }
    Ok(entries.into_iter().map(|(n, _)| n).collect())
}

fn packet_ids(packets: &Value) -> Result<String> {
    let mut out = String::from(HEADER);
    out.push_str("// Packet ids by connection state and direction.\n");
    for state in ["handshake", "status", "login", "configuration", "play"] {
        writeln!(out, "pub mod {state} {{")?;
        for side in ["clientbound", "serverbound"] {
            let Some(list) = packets[state].get(side) else {
                continue;
            };
            writeln!(out, "pub mod {side} {{")?;
            let mut seen = HashMap::new();
            for (name, id) in entries_by_id(list, &format!("{state} {side}"))? {
                let konst = const_name(&name)?;
                if let Some(other) = seen.insert(konst.clone(), name.clone()) {
                    return Err(format!("{other} and {name} are both {konst}").into());
                }
                writeln!(out, "pub const {konst}: i32 = {id};")?;
            }
            out.push_str("}\n");
        }
        out.push_str("}\n");
    }
    Ok(out)
}

struct BlockDef {
    name: String,
    min_state: u32,
    default_state: u32,
    /// Sorted by name: the first is the most significant digit of a state id.
    props: Vec<(String, Vec<String>)>,
}

fn blocks(blocks: &Value, registries: &Value) -> Result<String> {
    let names = registry_names(registries, "minecraft:block")?;
    let json = blocks
        .as_object()
        .ok_or("blocks.json: expected an object")?;
    if names.len() != json.len() || names.iter().any(|n| !json.contains_key(n)) {
        return Err("blocks.json and the block registry list different blocks".into());
    }
    let defs = names
        .iter()
        .map(|n| block_def(n, &json[n]))
        .collect::<Result<Vec<_>>>()?;

    let mut next = 0;
    for b in &defs {
        if b.min_state != next {
            return Err(format!(
                "{}: states start at {}, expected {next}",
                b.name, b.min_state
            )
            .into());
        }
        next = b.min_state + b.props.iter().map(|(_, v)| v.len() as u32).product::<u32>();
    }
    let state_count =
        u16::try_from(next).map_err(|_| format!("{next} states do not fit in a u16"))?;

    // property definitions shared between blocks
    let mut shared: Vec<&(String, Vec<String>)> = Vec::new();
    let mut index: HashMap<&(String, Vec<String>), usize> = HashMap::new();
    for p in defs.iter().flat_map(|b| &b.props) {
        index.entry(p).or_insert_with(|| {
            shared.push(p);
            shared.len() - 1
        });
    }

    let mut out = String::from(HEADER);
    out.push_str("use crate::block::{Block, BlockInfo, Property};\n\n");
    for (i, (name, values)) in shared.iter().enumerate() {
        let values: Vec<String> = values.iter().map(|v| format!("{v:?}")).collect();
        writeln!(
            out,
            "static P{i}: Property = Property {{ name: {name:?}, values: &[{}] }};",
            values.join(", ")
        )?;
    }
    writeln!(out, "\npub static BLOCKS: [BlockInfo; {}] = [", defs.len())?;
    for b in &defs {
        let props: Vec<String> = b.props.iter().map(|p| format!("&P{}", index[p])).collect();
        writeln!(
            out,
            "BlockInfo {{ name: {:?}, min_state: {}, default_state: {}, properties: &[{}] }},",
            b.name,
            b.min_state,
            b.default_state,
            props.join(", ")
        )?;
    }
    writeln!(out, "];\n\npub const STATE_COUNT: u16 = {state_count};\n")?;
    let mut seen = HashMap::new();
    for (id, b) in defs.iter().enumerate() {
        let konst = const_name(&b.name)?;
        if let Some(other) = seen.insert(konst.clone(), &b.name) {
            return Err(format!("{other} and {} are both {konst}", b.name).into());
        }
        writeln!(out, "pub const {konst}: Block = Block({id});")?;
    }
    Ok(out)
}

/// Reads one block and checks that its state ids follow the mixed-radix rule.
fn block_def(name: &str, json: &Value) -> Result<BlockDef> {
    // serde_json's map is sorted by key, which is the order the game uses
    let props: Vec<(String, Vec<String>)> = json["properties"]
        .as_object()
        .into_iter()
        .flatten()
        .map(|(k, v)| {
            let values = v
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(Value::as_str)
                .map(str::to_owned);
            (k.clone(), values.collect())
        })
        .collect();

    let mut states: Vec<(u32, bool, BTreeMap<String, String>)> = Vec::new();
    for s in json["states"]
        .as_array()
        .ok_or_else(|| format!("{name}: no states"))?
    {
        let id = s["id"]
            .as_u64()
            .and_then(|id| u32::try_from(id).ok())
            .ok_or_else(|| format!("{name}: state without id"))?;
        let values = s["properties"]
            .as_object()
            .into_iter()
            .flatten()
            .map(|(k, v)| (k.clone(), v.as_str().unwrap_or_default().to_owned()))
            .collect();
        states.push((id, s["default"].as_bool().unwrap_or(false), values));
    }
    states.sort_by_key(|(id, ..)| *id);

    let expected_count: usize = props.iter().map(|(_, v)| v.len()).product();
    if states.len() != expected_count {
        return Err(format!(
            "{name}: {} states, but its properties give {expected_count}",
            states.len()
        )
        .into());
    }
    let min_state = states
        .first()
        .map(|(id, ..)| *id)
        .ok_or_else(|| format!("{name}: no states"))?;
    for (i, (id, _, values)) in states.iter().enumerate() {
        if *id != min_state + i as u32 {
            return Err(format!("{name}: state ids are not consecutive at {id}").into());
        }
        let mut rest = i;
        let mut expected = BTreeMap::new();
        for (prop, all) in props.iter().rev() {
            expected.insert(prop.clone(), all[rest % all.len()].clone());
            rest /= all.len();
        }
        if *values != expected {
            return Err(format!(
                "{name}: state {id} is {values:?}, the mixed-radix rule gives {expected:?}"
            )
            .into());
        }
    }
    let mut defaults = states.iter().filter(|(_, d, _)| *d);
    let default_state = match (defaults.next(), defaults.next()) {
        (Some((id, ..)), None) => *id,
        _ => return Err(format!("{name}: expected exactly one default state").into()),
    };
    Ok(BlockDef {
        name: name.to_owned(),
        min_state,
        default_state,
        props,
    })
}

fn entity_types(registries: &Value) -> Result<String> {
    let names = registry_names(registries, "minecraft:entity_type")?;
    let mut out = String::from(HEADER);
    out.push_str("use crate::entity_type::EntityType;\n\n");
    let list: Vec<String> = names.iter().map(|n| format!("{n:?}")).collect();
    writeln!(
        out,
        "pub static ENTITY_TYPE_NAMES: [&str; {}] = [{}];\n",
        names.len(),
        list.join(", ")
    )?;
    let mut seen = HashMap::new();
    for (id, name) in names.iter().enumerate() {
        let konst = const_name(name)?;
        if let Some(other) = seen.insert(konst.clone(), name) {
            return Err(format!("{other} and {name} are both {konst}").into());
        }
        writeln!(out, "pub const {konst}: EntityType = EntityType({id});")?;
    }
    Ok(out)
}

fn datapack_registries(registries: &[(String, Vec<String>)]) -> Result<String> {
    let mut out = String::from(HEADER);
    out.push_str("/// `(registry id, entry names)`. Entry order is the network id order.\n");
    writeln!(
        out,
        "pub static DATAPACK_REGISTRIES: [(&str, &[&str]); {}] = [",
        registries.len()
    )?;
    for (id, names) in registries {
        let list: Vec<String> = names.iter().map(|n| format!("{n:?}")).collect();
        writeln!(out, "({id:?}, &[{}]),", list.join(", "))?;
    }
    out.push_str("];\n");
    Ok(out)
}

/// Expands `#tag` references so every tag is a flat list of entry names.
fn flatten(
    tags: &BTreeMap<String, Vec<String>>,
    tag: &str,
    stack: &mut Vec<String>,
) -> Result<Vec<String>> {
    if stack.iter().any(|t| t == tag) {
        return Err(format!("tag cycle through {tag}").into());
    }
    let values = tags.get(tag).ok_or_else(|| format!("unknown tag #{tag}"))?;
    stack.push(tag.to_owned());
    let mut out: Vec<String> = Vec::new();
    for v in values {
        let names = match v.strip_prefix('#') {
            Some(r) => flatten(
                tags,
                r.strip_prefix("minecraft:")
                    .ok_or("tag from another namespace")?,
                stack,
            )?,
            None => vec![v.clone()],
        };
        for n in names {
            if !out.contains(&n) {
                out.push(n);
            }
        }
    }
    stack.pop();
    Ok(out)
}

/// `STATIC_TAGS` (entry ids, from `registries.json`) and `DYNAMIC_TAGS` (entry names, to be
/// resolved against the registry the server actually sends).
fn tags(input: &Input) -> Result<String> {
    let mut static_out = Vec::new();
    let mut dynamic_out = Vec::new();
    for (registry, tags) in &input.tags {
        let id = format!("minecraft:{registry}");
        let mut flat = Vec::new();
        for tag in tags.keys() {
            flat.push((tag, flatten(tags, tag, &mut Vec::new())?));
        }
        if input.registries.get(&id).is_some() {
            let ids: std::collections::HashMap<String, u32> =
                entries_by_id(&input.registries[&id]["entries"], &id)?
                    .into_iter()
                    .collect();
            let mut rows = Vec::new();
            for (tag, names) in flat {
                let mut list = Vec::new();
                for n in names {
                    let i = ids
                        .get(&n)
                        .ok_or_else(|| format!("tag #{tag} in {id} names unknown entry {n}"))?;
                    list.push(i.to_string());
                }
                rows.push(format!(
                    "({:?}, &[{}])",
                    format!("minecraft:{tag}"),
                    list.join(", ")
                ));
            }
            static_out.push(format!("({id:?}, &[{}])", rows.join(", ")));
        } else {
            let (_, entries) = input
                .datapack_registries
                .iter()
                .find(|(r, _)| *r == id)
                .ok_or_else(|| format!("tags for {id}, which is neither static nor synced"))?;
            let mut rows = Vec::new();
            for (tag, names) in flat {
                for n in &names {
                    if !entries.contains(n) {
                        return Err(format!("tag #{tag} in {id} names unknown entry {n}").into());
                    }
                }
                let list: Vec<String> = names.iter().map(|n| format!("{n:?}")).collect();
                rows.push(format!(
                    "({:?}, &[{}])",
                    format!("minecraft:{tag}"),
                    list.join(", ")
                ));
            }
            dynamic_out.push(format!("({id:?}, &[{}])", rows.join(", ")));
        }
    }
    let mut out = String::from(HEADER);
    out.push_str("/// `[(tag, entries)]` for one registry.\n");
    out.push_str("pub type TagTable<T> = &'static [(&'static str, &'static [T])];\n\n");
    out.push_str("/// `(registry, [(tag, entry ids)])` for registries with fixed ids.\n");
    writeln!(
        out,
        "pub static STATIC_TAGS: [(&str, TagTable<u32>); {}] = [{}];\n",
        static_out.len(),
        static_out.join(", ")
    )?;
    out.push_str(
        "/// `(registry, [(tag, entry names)])` for registries whose ids the server decides.\n",
    );
    writeln!(
        out,
        "pub static DYNAMIC_TAGS: [(&str, TagTable<&str>); {}] = [{}];",
        dynamic_out.len(),
        dynamic_out.join(", ")
    )?;
    Ok(out)
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn tag_references_are_expanded_and_cycles_are_rejected() {
        let tags = |rows: &[(&str, &[&str])]| -> BTreeMap<String, Vec<String>> {
            rows.iter()
                .map(|(t, v)| (t.to_string(), v.iter().map(|s| s.to_string()).collect()))
                .collect()
        };
        let ok = tags(&[
            ("a", &["minecraft:x", "#minecraft:b"]),
            ("b", &["minecraft:y", "minecraft:x"]),
        ]);
        assert_eq!(
            flatten(&ok, "a", &mut Vec::new()).unwrap(),
            ["minecraft:x", "minecraft:y"]
        );
        let cyc = tags(&[("a", &["#minecraft:b"]), ("b", &["#minecraft:a"])]);
        assert!(flatten(&cyc, "a", &mut Vec::new()).is_err());
        assert!(flatten(&ok, "missing", &mut Vec::new()).is_err());
    }

    fn registry(names: &[&str]) -> Value {
        let entries: serde_json::Map<String, Value> = names
            .iter()
            .enumerate()
            .map(|(i, n)| (n.to_string(), json!({ "protocol_id": i })))
            .collect();
        json!({ "minecraft:block": { "entries": entries } })
    }

    fn two_property_block(order: [usize; 4]) -> Value {
        // x is the most significant digit: (p,0) (p,1) (q,0) (q,1)
        let all = [("p", "0"), ("p", "1"), ("q", "0"), ("q", "1")];
        let states: Vec<Value> = order
            .iter()
            .enumerate()
            .map(|(id, &i)| json!({ "id": id + 1, "default": id == 0, "properties": { "x": all[i].0, "y": all[i].1 } }))
            .collect();
        json!({ "properties": { "y": ["0", "1"], "x": ["p", "q"] }, "states": states })
    }

    #[test]
    fn constant_names() {
        assert_eq!(const_name("minecraft:oak_stairs").unwrap(), "OAK_STAIRS");
        assert_eq!(const_name("minecraft:a/b.c").unwrap(), "A_B_C");
        assert!(const_name("minecraft:1x").is_err());
    }

    #[test]
    fn accepts_the_mixed_radix_order_with_sorted_properties() {
        let json = json!({
            "minecraft:a": { "states": [{ "id": 0, "default": true }] },
            "minecraft:b": two_property_block([0, 1, 2, 3]),
        });
        let out = blocks(&json, &registry(&["minecraft:a", "minecraft:b"])).unwrap();
        assert!(out.contains("pub const STATE_COUNT: u16 = 5;"));
        // x sorts before y even though the file lists y first
        assert!(out.contains("static P0: Property = Property { name: \"x\""));
        assert!(out.contains("pub const B: Block = Block(1);"));
    }

    #[test]
    fn rejects_states_that_break_the_rule() {
        let json = json!({
            "minecraft:a": { "states": [{ "id": 0, "default": true }] },
            "minecraft:b": two_property_block([0, 2, 1, 3]),
        });
        let err = blocks(&json, &registry(&["minecraft:a", "minecraft:b"]))
            .unwrap_err()
            .to_string();
        assert!(
            err.contains("minecraft:b") && err.contains("mixed-radix"),
            "{err}"
        );
    }

    #[test]
    fn rejects_gaps_and_missing_defaults() {
        let gap = json!({ "minecraft:a": { "states": [{ "id": 1, "default": true }] } });
        assert!(blocks(&gap, &registry(&["minecraft:a"])).is_err());
        let no_default = json!({ "minecraft:a": { "states": [{ "id": 0 }] } });
        assert!(blocks(&no_default, &registry(&["minecraft:a"])).is_err());
        let sparse =
            json!({ "minecraft:block": { "entries": { "minecraft:a": { "protocol_id": 1 } } } });
        assert!(registry_names(&sparse, "minecraft:block").is_err());
    }

    #[test]
    fn packet_ids_are_grouped_by_state_and_side() {
        let packets = json!({
            "handshake": { "serverbound": { "minecraft:intention": { "protocol_id": 0 } } },
            "play": { "clientbound": { "minecraft:b": { "protocol_id": 1 }, "minecraft:a": { "protocol_id": 0 } } },
        });
        let out = packet_ids(&packets).unwrap();
        assert!(
            out.contains(
                "pub mod handshake {\npub mod serverbound {\npub const INTENTION: i32 = 0;"
            )
        );
        assert!(
            out.find("pub const A: i32 = 0;").unwrap() < out.find("pub const B: i32 = 1;").unwrap()
        );
        let dup = json!({ "play": { "clientbound": { "minecraft:x.y": { "protocol_id": 0 }, "minecraft:x_y": { "protocol_id": 1 } } } });
        assert!(packet_ids(&dup).is_err());
    }
}
